apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compressor-input
  namespace: compressor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compressor-output
  namespace: compressor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
