apiVersion: v1
kind: Service
metadata:
  name: compressor
  namespace: compressor
  labels:
    app: compressor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: compressor
